language: php

php:
  - '7.0'
  - '7.1'

before_script:
  - composer update --prefer-dist

before_deploy:
  - make env_key=$env_key decrpyt-env
  - chmod +x $TRAVIS_BUILD_DIR/docs/ecs/deploy.sh

deploy:
  skip_cleanup: true
  provider: script
  script: sh $TRAVIS_BUILD_DIR/docs/ecs/deploy.sh
  on:
    branch: feature/ecs-deploy2

notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/e7b990a7f895fb0aca02
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: never     # options: [always|never|change] default: always
