version: '2'

services:
  web:
    image: ${DOCKER_REPO}:${DOCKER_TAG}
    volumes:
      - /tmp/intranet:/tmp/
    ports:
      - ${INTRA_WEBPORT}:80
    cpu_shares: 100
    mem_limit: 104857600 # 100MB
    environment:
      DOMAIN: ${DOMAIN}
      IS_DEV: 0
      TEST_ID: ${TEST_ID}
      TEST_MAILS: ${TEST_MAILS}
      INTRA_DBHOST: ${INTRA_DBHOST}
      INTRA_DBUSER: ${INTRA_DBUSER}
      INTRA_DBPASS: ${INTRA_DBPASS}
      INTRA_DBNAME: ${INTRA_DBNAME}
      AZURE_CLIENTID: ${AZURE_CLIENTID}
      AZURE_PASSWORD: ${AZURE_PASSWORD}
      AZURE_REDIRECT_URI: ${AZURE_REDIRECT_URI}
      AZURE_RESOURCE_URI: ${AZURE_RESOURCE_URI}
      AZURE_APPTENANT_DOMAINNAME: ${AZURE_APPTENANT_DOMAINNAME}
      AZURE_API_VERSION: ${AZURE_API_VERSION}
      AWS_ACCESS_KEY: ${AWS_ACCESS_KEY}
      AWS_SECRET_KEY: ${AWS_SECRET_KEY}
      AWS_REGION: ${AWS_REGION}
      AWS_S3_BUCKET: ${AWS_S3_BUCKET}
      SENTRY_KEY: ${SENTRY_KEY}
      SENTRY_PUBLIC_KEY: ${SENTRY_PUBLIC_KEY}
      RIDI_IPS: ${RIDI_IPS}
      TRUSTED_PROXIES: ${TRUSTED_PROXIES}
      MAILGUN_API_KEY: ${MAILGUN_API_KEY}
      MAILGUN_FROM: ${MAILGUN_FROM}
